##Importing Libraries and the Dataset

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("/content/drive/MyDrive/Mini Project/preprocessed_data.csv")

In [4]:
df.head()

Unnamed: 0         short_name  ...  overall  potential
0           0           L. Messi  ...       93         93
1           1  Cristiano Ronaldo  ...       92         92
2           2           J. Oblak  ...       91         93
3           3     R. Lewandowski  ...       91         91
4           4          Neymar Jr  ...       91         91

[5 rows x 59 columns]

In [5]:
nr = df.columns[[0,2,3]]

In [6]:
df.drop(nr,axis=1,inplace=True)

In [7]:
df.head()

short_name  preferred_foot  ...  overall  potential
0           L. Messi               0  ...       93         93
1  Cristiano Ronaldo               1  ...       92         92
2           J. Oblak               1  ...       91         93
3     R. Lewandowski               1  ...       91         91
4          Neymar Jr               1  ...       91         91

[5 rows x 56 columns]

In [8]:
df.shape

(18719, 56)

In [9]:
df.work_rate.unique()

array([7, 1, 8, 2, 0, 6, 3, 5, 4])

In [10]:
df.team_position.unique()

array([ 0, 13,  5, 27, 14, 19,  8, 25, 28,  3,  2, 20, 24,  9, 17,  7, 12,
       18, 11,  1, 23, 10, 22, 21, 15,  4,  6, 26, 16])

In [11]:
df.preferred_foot.unique()

array([0, 1])

##Traing Model

In [12]:
X1 = df.iloc[:,1:53].values
X2 = df.iloc[:,2:53].values
X3 = df.iloc[:,2:53].values
y1 = df.iloc[:,53].values
y2 = df.iloc[:,54].values
y3 = df.iloc[:,55].values

In [13]:
print(y2)

[93 92 91 ... 47 47 47]


In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X1 = sc.fit_transform(X1)
X2 = sc.fit_transform(X2)
X3 = sc.fit_transform(X3)

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel='rbf',random_state=0)
classifier.fit(X1,y1)

SVC(random_state=0)

In [39]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 1)
X2_poly = poly_reg.fit_transform(X2)
lin_reg = LinearRegression()
regressor1 = lin_reg.fit(X2_poly,y2)

In [43]:
poly_reg_ = PolynomialFeatures(degree = 1)
X3_poly = poly_reg_.fit_transform(X3)
lin_reg = LinearRegression()
regressor2 = lin_reg.fit(X3_poly,y3)

##Importing the Non-Professional Player dataset

In [16]:
df2 = pd.read_csv("/content/drive/MyDrive/Mini Project/non-professional - non-professional.csv")
df2.head()

short_name preferred_foot  ... overall  potential
0       Ilias Akhomach           Left  ...     NaN        NaN
1              Ez Abde          Right  ...     NaN        NaN
2      Matheus Pereira           Left  ...     NaN        NaN
3  Maarten Vandevoordt          Right  ...     NaN        NaN
4        M Morgenstern          Right  ...     NaN        NaN

[5 rows x 56 columns]

##Encoding the Categorical Data

In [17]:
objList = df2.select_dtypes(include = "object").columns
print (objList)

Index(['short_name', 'preferred_foot', 'team_position', 'work_rate'], dtype='object')


In [18]:
a = {'Medium/Low':7, 'High/Low':1, 'Medium/Medium':8, 'High/Medium':2,
       'High/High':0, 'Medium/High':6, 'Low/High':3, 'Low/Medium':5, 'Low/Low':4}
b = {'CAM':0, 'LS':13, 'GK':5, 'ST':27, 'LW':14, 'RCM':19, 'LCB':8, 'RW':25, 'SUB':28, 'CF':3,
       'CDM':2, 'RDM':20, 'RS':24, 'LCM':9, 'RB':17, 'LB':7, 'LM':12, 'RCB':18, 'LF':11, 'CB':1,
       'RM':23, 'LDM':10, 'RF':22, 'RES':21, 'LWB':15, 'CM':4, 'LAM':6, 'RWB':26, 'RAM':16}
c = {'Left':0,'Right':1}
df2['work_rate'] = df2['work_rate'].map(a)
df2['team_position'] = df2['team_position'].map(b)
df2['preferred_foot'] = df2['preferred_foot'].map(c)

In [27]:
df2

short_name  preferred_foot  ...  overall  potential
0       Ilias Akhomach               0  ...      NaN        NaN
1              Ez Abde               1  ...      NaN        NaN
2      Matheus Pereira               0  ...      NaN        NaN
3  Maarten Vandevoordt               1  ...      NaN        NaN
4        M Morgenstern               1  ...      NaN        NaN
5              V dican               1  ...      NaN        NaN
6              J seelt               0  ...      NaN        NaN
7             L Stanga               1  ...      NaN        NaN
8          Manu Martos               0  ...      NaN        NaN

[9 rows x 56 columns]

##Predicting the Result

In [20]:
df2.columns.get_loc('player_positions')

53

In [21]:
X1_ = df2.iloc[:,1:53].values
X2_ = df2.iloc[:,2:53].values

In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X1_ = sc.fit_transform(X1_)
X2_ = sc.fit_transform(X2_)

In [ ]:
y1_pred = classifier.predict(X1_)

In [ ]:
df2['player_positions'][0]

In [ ]:
for i in range(len(y1_pred)):
  df2['player_positions'][i] = y1_pred[i]

In [ ]:
df2.head()

In [40]:
y_pred = regressor1.predict(poly_reg.fit_transform(X2_))

In [41]:
print(y_pred)

[72.21169788 77.52086023 78.62027794 69.43132286 78.38848478 46.51624409
 59.93552346 60.68449262 47.4063053 ]


In [44]:
y_pred2 = regressor2.predict(poly_reg_.fit_transform(X2_))

In [45]:
print(y_pred2)

[85.15480786 82.98063232 77.02212705 74.50161017 87.01374047 50.62254516
 70.77798956 66.74304217 44.9907599 ]
