##Importing Libraries and dataset

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Mini Project/players_21.csv")

In [ ]:
pd.set_option("display.max_columns",None)

In [ ]:
df.head()

sofifa_id                                         player_url  \
0     158023  https://sofifa.com/player/158023/lionel-messi/...   
1      20801  https://sofifa.com/player/20801/c-ronaldo-dos-...   
2     200389  https://sofifa.com/player/200389/jan-oblak/210002   
3     188545  https://sofifa.com/player/188545/robert-lewand...   
4     190871  https://sofifa.com/player/190871/neymar-da-sil...   

          short_name                            long_name  age         dob  \
0           L. Messi       Lionel Andrés Messi Cuccittini   33  1987-06-24   
1  Cristiano Ronaldo  Cristiano Ronaldo dos Santos Aveiro   35  1985-02-05   
2           J. Oblak                            Jan Oblak   27  1993-01-07   
3     R. Lewandowski                   Robert Lewandowski   31  1988-08-21   
4          Neymar Jr        Neymar da Silva Santos Júnior   28  1992-02-05   

   height_cm  weight_kg nationality            club_name  \
0        170         72   Argentina         FC Barcelona   
1        187         83    Portugal             Juventus   
2        188         87    Slovenia      Atlético Madrid   
3        184         80      Poland    FC Bayern München   
4        175         68      Brazil  Paris Saint-Germain   

              league_name  league_rank  overall  potential  value_eur  \
0  Spain Primera Division          1.0       93         93   67500000   
1         Italian Serie A          1.0       92         92   46000000   
2  Spain Primera Division          1.0       91         93   75000000   
3    German 1. Bundesliga          1.0       91         91   80000000   
4          French Ligue 1          1.0       91         91   90000000   

   wage_eur player_positions preferred_foot  international_reputation  \
0    560000       RW, ST, CF           Left                         5   
1    220000           ST, LW          Right                         5   
2    125000               GK          Right                         3   
3    240000               ST          Right                         4   
4    270000          LW, CAM          Right                         5   

   weak_foot  skill_moves      work_rate             body_type real_face  \
0          4            4     Medium/Low                 Messi       Yes   
1          4            5       High/Low            C. Ronaldo       Yes   
2          3            1  Medium/Medium  PLAYER_BODY_TYPE_259       Yes   
3          4            4    High/Medium  PLAYER_BODY_TYPE_276       Yes   
4          5            5    High/Medium                Neymar       Yes   

   release_clause_eur                                        player_tags  \
0         138400000.0  #Dribbler, #Distance Shooter, #FK Specialist, ...   
1          75900000.0  #Aerial Threat, #Dribbler, #Distance Shooter, ...   
2         159400000.0                                                NaN   
3         132000000.0              #Distance Shooter, #Clinical Finisher   
4         166500000.0  #Speedster, #Dribbler, #Playmaker, #FK Special...   

  team_position  team_jersey_number loaned_from      joined  \
0           CAM                10.0         NaN  2004-07-01   
1            LS                 7.0         NaN  2018-07-10   
2            GK                13.0         NaN  2014-07-16   
3            ST                 9.0         NaN  2014-07-01   
4            LW                10.0         NaN  2017-08-03   

   contract_valid_until nation_position  nation_jersey_number  pace  shooting  \
0                2021.0              RW                  10.0  85.0      92.0   
1                2022.0              LS                   7.0  89.0      93.0   
2                2023.0              GK                   1.0   NaN       NaN   
3                2023.0             NaN                   NaN  78.0      91.0   
4                2022.0             NaN                   NaN  91.0      85.0   

   passing  dribbling  defending  physic  gk_diving  gk_handling  gk_kicking  \
0     91.0       95.0       38.0

In [ ]:
df.shape

(18944, 106)

##Dropping Irrelevent Columns

In [ ]:
df.columns.get_loc('preferred_foot')

17

In [ ]:
nr = df.columns[[0,1,3,5,6,7,8,9,10,11,18,22,23,24,25,28,29,30,31,32,45,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105]]

In [ ]:
df.drop(nr,inplace=True,axis=1)
df.shape

(18944, 59)

In [ ]:
df.head()

short_name  age  overall  potential  value_eur  wage_eur  \
0           L. Messi   33       93         93   67500000    560000   
1  Cristiano Ronaldo   35       92         92   46000000    220000   
2           J. Oblak   27       91         93   75000000    125000   
3     R. Lewandowski   31       91         91   80000000    240000   
4          Neymar Jr   28       91         91   90000000    270000   

  player_positions preferred_foot  weak_foot  skill_moves      work_rate  \
0       RW, ST, CF           Left          4            4     Medium/Low   
1           ST, LW          Right          4            5       High/Low   
2               GK          Right          3            1  Medium/Medium   
3               ST          Right          4            4    High/Medium   
4          LW, CAM          Right          5            5    High/Medium   

  team_position  team_jersey_number  pace  shooting  passing  dribbling  \
0           CAM                10.0  85.0      92.0     91.0       95.0   
1            LS                 7.0  89.0      93.0     81.0       89.0   
2            GK                13.0   NaN       NaN      NaN        NaN   
3            ST                 9.0  78.0      91.0     78.0       85.0   
4            LW                10.0  91.0      85.0     86.0       94.0   

   defending  physic  gk_diving  gk_handling  gk_kicking  gk_reflexes  \
0       38.0    65.0        NaN          NaN         NaN          NaN   
1       35.0    77.0        NaN          NaN         NaN          NaN   
2        NaN     NaN       87.0         92.0        78.0         90.0   
3       43.0    82.0        NaN          NaN         NaN          NaN   
4       36.0    59.0        NaN          NaN         NaN          NaN   

   gk_speed  gk_positioning  attacking_crossing  attacking_finishing  \
0       NaN             NaN                  85                   95   
1       NaN             NaN                  84                   95   
2      52.0            90.0                  13                   11   
3       NaN             NaN                  71                   94   
4       NaN             NaN                  85                   87   

   attacking_heading_accuracy  attacking_short_passing  attacking_volleys  \
0                          70                       91                 88   
1                          90                       82                 86   
2                          15                       43                 13   
3                          85                       84                 89   
4                          62                       87                 87   

   skill_dribbling  skill_curve  skill_fk_accuracy  skill_long_passing  \
0               96           93                 94                  91   
1               88           81                 76                  77   
2               12           13                 14                  40   
3               85           79                 85                  70   
4               95           88                 89                  81   

   skill_ball_control  movement_acceleration  movement_sprint_speed  \
0                  96                     91                     80   
1                  92                     87                     91   
2                  30                     43                     60   
3                  88                     77                     78   
4                  95                     94                     89   

   movement_agility  movement_reactions  movement_balance  power_shot_power  \
0                91                  94                95                86   
1                87                  95                71                94   
2                67                  88                49                59   
3                77                  93                82                89   
4                96                  91                83                80   


##Handling Missing Data

In [ ]:
df.isnull().sum()

short_name                        0
age                               0
overall                           0
potential                         0
value_eur                         0
wage_eur                          0
player_positions                  0
preferred_foot                    0
weak_foot                         0
skill_moves                       0
work_rate                         0
team_position                   225
team_jersey_number              225
pace                           2083
shooting                       2083
passing                        2083
dribbling                      2083
defending                      2083
physic                         2083
gk_diving                     16861
gk_handling                   16861
gk_kicking                    16861
gk_reflexes                   16861
gk_speed                      16861
gk_positioning                16861
attacking_crossing                0
attacking_finishing               0
attacking_heading_accuracy  

In [ ]:
b = df['team_position'].isnull()
len(b)

18944

In [ ]:
a = []
for i in range(len(b)):
    if b[i]==True:
        a.append(i)
print(a)       

[359, 363, 494, 495, 496, 497, 498, 499, 500, 501, 502, 528, 583, 626, 679, 680, 681, 682, 895, 896, 897, 999, 1027, 1037, 1172, 1173, 1174, 1175, 1176, 1338, 1367, 1424, 1432, 1453, 1479, 1495, 1496, 1497, 1588, 1842, 1947, 2034, 2035, 2036, 2038, 2039, 2180, 2433, 2442, 2487, 2564, 2589, 2605, 2613, 2629, 2697, 2706, 2781, 2844, 2885, 2955, 2992, 3001, 3057, 3058, 3359, 3403, 3499, 3539, 3562, 3623, 3664, 3677, 3708, 3734, 3801, 3802, 3803, 3804, 3881, 3989, 4086, 4088, 4344, 4358, 4387, 4401, 4410, 4501, 4715, 4747, 4781, 4791, 4805, 4855, 4881, 4970, 5004, 5128, 5165, 5208, 5209, 5234, 5243, 5356, 5391, 5392, 5409, 5471, 5620, 5666, 5691, 5792, 5794, 5817, 5838, 5845, 5909, 5920, 5951, 6073, 6127, 6153, 6208, 6210, 6214, 6241, 6318, 6328, 6329, 6816, 6852, 6936, 6940, 7074, 7100, 7197, 7302, 7303, 7354, 7689, 7811, 7888, 7944, 7955, 7960, 7988, 8180, 8242, 8283, 8319, 8368, 8412, 8425, 8851, 8925, 8990, 9154, 9186, 9198, 9317, 9320, 9334, 9356, 9498, 9538, 9828, 10321, 10491, 10527

In [ ]:
df.drop(a,inplace=True)

In [ ]:
df.columns.get_loc('defending_marking')

51

In [ ]:
nr1 = df.columns[[51]]
df.drop(nr1,axis=1,inplace=True)

In [ ]:
df.isnull().sum()

short_name                        0
age                               0
overall                           0
potential                         0
value_eur                         0
wage_eur                          0
player_positions                  0
preferred_foot                    0
weak_foot                         0
skill_moves                       0
work_rate                         0
team_position                     0
team_jersey_number                0
pace                           2053
shooting                       2053
passing                        2053
dribbling                      2053
defending                      2053
physic                         2053
gk_diving                     16666
gk_handling                   16666
gk_kicking                    16666
gk_reflexes                   16666
gk_speed                      16666
gk_positioning                16666
attacking_crossing                0
attacking_finishing               0
attacking_heading_accuracy  

In [ ]:
df.columns.get_loc('gk_positioning')

24

In [ ]:
val=df.columns.values.tolist()
val1 = val[13:19]
val2 = val[19:25]
for i in range(len(val1)):
    df[val1[i]].fillna(30,inplace=True)
for j in range(len(val2)):
    df[val2[j]].fillna(10,inplace=True)

In [ ]:
df.isnull().sum()

short_name                    0
age                           0
overall                       0
potential                     0
value_eur                     0
wage_eur                      0
player_positions              0
preferred_foot                0
weak_foot                     0
skill_moves                   0
work_rate                     0
team_position                 0
team_jersey_number            0
pace                          0
shooting                      0
passing                       0
dribbling                     0
defending                     0
physic                        0
gk_diving                     0
gk_handling                   0
gk_kicking                    0
gk_reflexes                   0
gk_speed                      0
gk_positioning                0
attacking_crossing            0
attacking_finishing           0
attacking_heading_accuracy    0
attacking_short_passing       0
attacking_volleys             0
skill_dribbling               0
skill_cu

##Organizing the dataset

In [ ]:
i = df.pop('player_positions')
df['player_positions'] = i

In [ ]:
j = df.pop('overall')
df['overall'] = j

In [ ]:
k = df.pop('potential')
df['potential'] = k

In [ ]:
m = df.pop('team_position')
df.insert(5,'team_position',m)

In [ ]:
n = df.pop('age')

In [ ]:
df.insert(7,'age',n)

In [ ]:
df.head()

short_name  value_eur  wage_eur preferred_foot team_position  \
0           L. Messi   67500000    560000           Left           CAM   
1  Cristiano Ronaldo   46000000    220000          Right            LS   
2           J. Oblak   75000000    125000          Right            GK   
3     R. Lewandowski   80000000    240000          Right            ST   
4          Neymar Jr   90000000    270000          Right            LW   

   weak_foot  skill_moves  age      work_rate  team_jersey_number  pace  \
0          4            4   33     Medium/Low                10.0  85.0   
1          4            5   35       High/Low                 7.0  89.0   
2          3            1   27  Medium/Medium                13.0  30.0   
3          4            4   31    High/Medium                 9.0  78.0   
4          5            5   28    High/Medium                10.0  91.0   

   shooting  passing  dribbling  defending  physic  gk_diving  gk_handling  \
0      92.0     91.0       95.0       38.0    65.0       10.0         10.0   
1      93.0     81.0       89.0       35.0    77.0       10.0         10.0   
2      30.0     30.0       30.0       30.0    30.0       87.0         92.0   
3      91.0     78.0       85.0       43.0    82.0       10.0         10.0   
4      85.0     86.0       94.0       36.0    59.0       10.0         10.0   

   gk_kicking  gk_reflexes  gk_speed  gk_positioning  attacking_crossing  \
0        10.0         10.0      10.0            10.0                  85   
1        10.0         10.0      10.0            10.0                  84   
2        78.0         90.0      52.0            90.0                  13   
3        10.0         10.0      10.0            10.0                  71   
4        10.0         10.0      10.0            10.0                  85   

   attacking_finishing  attacking_heading_accuracy  attacking_short_passing  \
0                   95                          70                       91   
1                   95                          90                       82   
2                   11                          15                       43   
3                   94                          85                       84   
4                   87                          62                       87   

   attacking_volleys  skill_dribbling  skill_curve  skill_fk_accuracy  \
0                 88               96           93                 94   
1                 86               88           81                 76   
2                 13               12           13                 14   
3                 89               85           79                 85   
4                 87               95           88                 89   

   skill_long_passing  skill_ball_control  movement_acceleration  \
0                  91                  96                     91   
1                  77                  92                     87   
2                  40                  30                     43   
3                  70                  88                     77   
4                  81                  95                     94   

   movement_sprint_speed  movement_agility  movement_reactions  \
0                     80                91                  94   
1                     91                87                  95   
2                     60                67                  88   
3                     78                77                  93   
4                     89                96                  91   

   movement_balance  power_shot_power  power_jumping  power_stamina  \
0                95                86             68             72   
1                71                94             95             84   
2                49                59             78             41   
3                82                89             84             76   
4                83                80             62             81   

   power_strength  power_long_shots  ment

##Encoding of Categorical Data

In [ ]:
objList = df.select_dtypes(include = "object").columns
print (objList)

Index(['short_name', 'preferred_foot', 'team_position', 'work_rate',
       'player_positions'],
      dtype='object')


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df['work_rate'] = le.fit_transform(df['work_rate'].astype(str))
df['team_position'] = le.fit_transform(df['team_position'].astype(str))
df['preferred_foot'] = le.fit_transform(df['preferred_foot'].astype(str))

In [ ]:
df.head()

short_name  value_eur  wage_eur  preferred_foot  team_position  \
0           L. Messi   67500000    560000               0              0   
1  Cristiano Ronaldo   46000000    220000               1             13   
2           J. Oblak   75000000    125000               1              5   
3     R. Lewandowski   80000000    240000               1             27   
4          Neymar Jr   90000000    270000               1             14   

   weak_foot  skill_moves  age  work_rate  team_jersey_number  pace  shooting  \
0          4            4   33          7                10.0  85.0      92.0   
1          4            5   35          1                 7.0  89.0      93.0   
2          3            1   27          8                13.0  30.0      30.0   
3          4            4   31          2                 9.0  78.0      91.0   
4          5            5   28          2                10.0  91.0      85.0   

   passing  dribbling  defending  physic  gk_diving  gk_handling  gk_kicking  \
0     91.0       95.0       38.0    65.0       10.0         10.0        10.0   
1     81.0       89.0       35.0    77.0       10.0         10.0        10.0   
2     30.0       30.0       30.0    30.0       87.0         92.0        78.0   
3     78.0       85.0       43.0    82.0       10.0         10.0        10.0   
4     86.0       94.0       36.0    59.0       10.0         10.0        10.0   

   gk_reflexes  gk_speed  gk_positioning  attacking_crossing  \
0         10.0      10.0            10.0                  85   
1         10.0      10.0            10.0                  84   
2         90.0      52.0            90.0                  13   
3         10.0      10.0            10.0                  71   
4         10.0      10.0            10.0                  85   

   attacking_finishing  attacking_heading_accuracy  attacking_short_passing  \
0                   95                          70                       91   
1                   95                          90                       82   
2                   11                          15                       43   
3                   94                          85                       84   
4                   87                          62                       87   

   attacking_volleys  skill_dribbling  skill_curve  skill_fk_accuracy  \
0                 88               96           93                 94   
1                 86               88           81                 76   
2                 13               12           13                 14   
3                 89               85           79                 85   
4                 87               95           88                 89   

   skill_long_passing  skill_ball_control  movement_acceleration  \
0                  91                  96                     91   
1                  77                  92                     87   
2                  40                  30                     43   
3                  70                  88                     77   
4                  81                  95                     94   

   movement_sprint_speed  movement_agility  movement_reactions  \
0                     80                91                  94   
1                     91                87                  95   
2                     60                67                  88   
3                     78                77                  93   
4                     89                96                  91   

   movement_balance  power_shot_power  power_jumping  power_stamina  \
0                95                86             68             72   
1                71                94             95             84   
2                49                59             78             41   
3                82                89             84             76   
4                83                80             62             81   

   power_strength  power_long_shots  mentality_aggres

##Exporting the preprocessed dataset

In [ ]:
import os 
os.makedirs("/content/drive/MyDrive/Mini Project",exist_ok=True)
df.to_csv("/content/drive/MyDrive/Mini Project/preprocessed_data.csv")
print("Data Exported Successfully!")

Data Exported Successfully!


##Selection of Data Subset

In [ ]:
X1 = df.iloc[:,3:55].values
X2 = df.iloc[:,4:55].values
X3 = df.iloc[:,4:55].values
y1 = df.iloc[:,55].values
y2 = df.iloc[:,56].values
y3 = df.iloc[:,57].values

In [ ]:
print(X1)

[[ 0.  0.  4. ... 15. 14.  8.]
 [ 1. 13.  4. ... 15. 14. 11.]
 [ 1.  5.  3. ... 78. 90. 90.]
 ...
 [ 1. 21.  2. ... 14. 15. 13.]
 [ 1. 20.  2. ...  7.  5. 13.]
 [ 1. 21.  2. ... 11.  5.  7.]]


In [ ]:
print(X2)

[[ 0.  4.  4. ... 15. 14.  8.]
 [13.  4.  5. ... 15. 14. 11.]
 [ 5.  3.  1. ... 78. 90. 90.]
 ...
 [21.  2.  2. ... 14. 15. 13.]
 [20.  2.  2. ...  7.  5. 13.]
 [21.  2.  2. ... 11.  5.  7.]]


In [ ]:
print(X3)

[[ 0.  4.  4. ... 15. 14.  8.]
 [13.  4.  5. ... 15. 14. 11.]
 [ 5.  3.  1. ... 78. 90. 90.]
 ...
 [21.  2.  2. ... 14. 15. 13.]
 [20.  2.  2. ...  7.  5. 13.]
 [21.  2.  2. ... 11.  5.  7.]]


In [ ]:
print(y1)

['RW, ST, CF' 'ST, LW' 'GK' ... 'CB' 'CM' 'CM']


In [ ]:
print(y2)

[93 92 91 ... 47 47 47]


In [ ]:
print(y3)

[93 92 93 ... 51 51 47]


##Splitting the data into training and testing data (for classification of player positions)

In [ ]:
from sklearn.model_selection import train_test_split
X1_train,X1_test,y1_train,y1_test = train_test_split(X1,y1,test_size=0.25,random_state=0)

##Scaling the data

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X1_train = sc.fit_transform(X1_train)
X1_test = sc.fit_transform(X1_test)

##Applying Classification Algorithms for finding the players position along with their accuracies

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier1 = KNeighborsClassifier(n_neighbors=55,metric='minkowski',p=2)
classifier1.fit(X1_train,y1_train)

KNeighborsClassifier(n_neighbors=55)

In [ ]:
y1_pred1 = classifier1.predict(X1_test)
print(np.concatenate((y1_pred1.reshape(len(y1_pred1),1),y1_test.reshape(len(y1_test),1)),1))

[['LB' 'LB, LM']
 ['CAM' 'CF, CM']
 ['ST' 'ST']
 ...
 ['RB' 'RB']
 ['ST' 'RW']
 ['ST' 'ST']]


In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm1 = confusion_matrix(y1_test,y1_pred1)
print(cm1)
accuracy_score1 = accuracy_score(y1_test,y1_pred1)
print("{:2f}".format(accuracy_score1))

[[14  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
0.470726


In [ ]:
from sklearn.svm import SVC
classifier2 = SVC(kernel='rbf',random_state=0)
classifier2.fit(X1_train,y1_train)

SVC(random_state=0)

In [ ]:
y1_pred2 = classifier2.predict(X1_test)
print(np.concatenate((y1_pred2.reshape(len(y1_pred2),1),y1_test.reshape(len(y1_test),1)),1))

[['LB' 'LB, LM']
 ['CAM, CM' 'CF, CM']
 ['ST' 'ST']
 ...
 ['RB' 'RB']
 ['ST' 'RW']
 ['ST' 'ST']]


In [ ]:
cm2 = confusion_matrix(y1_test,y1_pred2)
print(cm2)
accuracy_score2 = accuracy_score(y1_test,y1_pred2)
print("{:2f}".format(accuracy_score2))

[[32  0  0 ...  0  0  0]
 [ 1  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
0.495726


<i>rbf>linear>sigmoid (work) (accuracy)</i>

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier3 = GaussianNB()
classifier3.fit(X1_train,y1_train)

GaussianNB()

In [ ]:
y1_pred3 = classifier3.predict(X1_test)
print(np.concatenate((y1_pred3.reshape(len(y1_pred3),1),y1_test.reshape(len(y1_test),1)),1))

[['CM, RM, CDM' 'LB, LM']
 ['CAM, CM, LM' 'CF, CM']
 ['ST' 'ST']
 ...
 ['RB, LB' 'RB']
 ['CAM, CM, ST' 'RW']
 ['LW' 'ST']]


In [ ]:
cm3 = confusion_matrix(y1_test,y1_pred3)
print(cm3)
accuracy_score3 = accuracy_score(y1_test,y1_pred3)
print("{:2f}".format(accuracy_score3))

[[27  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
0.347222


In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier4 = DecisionTreeClassifier(criterion='entropy',random_state=0)
classifier4.fit(X1_train,y1_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [ ]:
y1_pred4 = classifier4.predict(X1_test)
print(np.concatenate((y1_pred4.reshape(len(y1_pred4),1),y1_test.reshape(len(y1_test),1)),1))

[['LM' 'LB, LM']
 ['CAM, RM, CM' 'CF, CM']
 ['ST' 'ST']
 ...
 ['CM, CDM' 'RB']
 ['RW, LWB, LW' 'RW']
 ['ST' 'ST']]


In [ ]:
cm4 = confusion_matrix(y1_test,y1_pred4)
print(cm4)
accuracy_score4 = accuracy_score(y1_test,y1_pred4)
print("{:2f}".format(accuracy_score4))

[[7 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
0.357265


In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier5 = RandomForestClassifier(n_estimators=50,criterion='entropy',random_state=0)
classifier5.fit(X1_train,y1_train)

RandomForestClassifier(criterion='entropy', n_estimators=50, random_state=0)

In [ ]:
y1_pred5 = classifier5.predict(X1_test)
print(np.concatenate((y1_pred5.reshape(len(y1_pred5),1),y1_test.reshape(len(y1_test),1)),1))

[['LB' 'LB, LM']
 ['CAM, CM' 'CF, CM']
 ['ST' 'ST']
 ...
 ['RB' 'RB']
 ['RM, CAM' 'RW']
 ['ST' 'ST']]


In [ ]:
cm5 = confusion_matrix(y1_test,y1_pred5)
print(cm5)
accuracy_score5 = accuracy_score(y1_test,y1_pred5)
print("{:2f}".format(accuracy_score5))

[[24  0  0 ...  0  0  0]
 [ 1  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
0.477778


###***Selected Algorithm - SVC (kernel-rbf)***

##Splitting data into training and testing (for overall rating of the player)

In [ ]:
from sklearn.model_selection import train_test_split
X2_train,X2_test,y2_train,y2_test = train_test_split(X2,y2,test_size=0.25,random_state=0)

##Applying regression algorithm to find the overall rating along with accuracy of the respective algorithm

In [ ]:
from sklearn.linear_model import LinearRegression
regressor1 = LinearRegression()
regressor1.fit(X2_train,y2_train)

LinearRegression()

In [ ]:
y2_pred1 = regressor1.predict(X2_test)
for i in range(len(y2_pred1)):
    y2_pred1[i] = round(y2_pred1[i])
print(np.concatenate((y2_pred1.reshape(len(y2_pred1),1),y2_test.reshape(len(y2_test),1)),1))

[[76. 76.]
 [66. 67.]
 [67. 66.]
 ...
 [66. 66.]
 [83. 83.]
 [58. 57.]]


In [ ]:
from sklearn.metrics import r2_score
r2_1 = r2_score(y2_test,y2_pred1)
print("{:.2f}".format(r2_1))

0.90


In [ ]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 2)
X2_poly = poly_reg.fit_transform(X2_train)
lin_reg = LinearRegression()
regressor2 = lin_reg.fit(X2_poly,y2_train)

In [ ]:
y2_pred2 = regressor2.predict(poly_reg.fit_transform(X2_test))
for i in range(len(y2_pred2)):
    y2_pred2[i] = round(y2_pred2[i])
print(np.concatenate((y2_pred2.reshape(len(y2_pred2),1),y2_test.reshape(len(y2_test),1)),1))

[[77. 76.]
 [68. 67.]
 [66. 66.]
 ...
 [66. 66.]
 [83. 83.]
 [57. 57.]]


In [ ]:
r2_2 = r2_score(y2_test,y2_pred2)
print("{:.3f}".format(r2_2))

0.973


In [ ]:
from sklearn.svm import SVR
regressor3 = SVR(kernel='rbf')
regressor3.fit(X2_train,y2_train)

SVR()

In [ ]:
y2_pred3 = regressor3.predict(X2_test)
for i in range(len(y2_pred3)):
    y2_pred3[i] = round(y2_pred3[i])
print(np.concatenate((y2_pred3.reshape(len(y2_pred3),1),y2_test.reshape(len(y2_test),1)),1))

[[77. 76.]
 [68. 67.]
 [66. 66.]
 ...
 [68. 66.]
 [83. 83.]
 [57. 57.]]


In [ ]:
r2_3 = r2_score(y2_test,y2_pred3)
print("{:.3f}".format(r2_3))

0.971


In [ ]:
from sklearn.tree import DecisionTreeRegressor
regressor4 = DecisionTreeRegressor(random_state=0)
regressor4.fit(X2_train,y2_train)

DecisionTreeRegressor(random_state=0)

In [ ]:
y2_pred4 = regressor4.predict(X2_test)
for i in range(len(y2_pred4)):
    y2_pred4[i] = round(y2_pred4[i])
print(np.concatenate((y2_pred4.reshape(len(y2_pred4),1),y2_test.reshape(len(y2_test),1)),1))

[[79. 76.]
 [64. 67.]
 [67. 66.]
 ...
 [69. 66.]
 [80. 83.]
 [56. 57.]]


In [ ]:
r2_4 = r2_score(y2_test,y2_pred4)
print("{:.3f}".format(r2_4))

0.912


In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor5 = RandomForestRegressor(n_estimators=40,random_state=0)
regressor5.fit(X2_train,y2_train)

RandomForestRegressor(n_estimators=40, random_state=0)

In [ ]:
y2_pred5 = regressor5.predict(X2_test)
for i in range(len(y2_pred5)):
    y2_pred5[i] = round(y2_pred5[i])
print(np.concatenate((y2_pred5.reshape(len(y2_pred5),1),y2_test.reshape(len(y2_test),1)),1))

[[77. 76.]
 [67. 67.]
 [67. 66.]
 ...
 [66. 66.]
 [81. 83.]
 [55. 57.]]


In [ ]:
r2_5 = r2_score(y2_test,y2_pred5)
print("{:.3f}".format(r2_5))

0.966


###***Selected Algorithm - Polynomial Regression***

##Splitting the data into training and testing (for potential rating)

In [ ]:
from sklearn.model_selection import train_test_split
X3_train,X3_test,y3_train,y3_test = train_test_split(X2,y2,test_size=0.25,random_state=0)

##Applying regression algorithms to find the potential ratings of the player along with the accuracies of the respective algorithm

In [ ]:
from sklearn.linear_model import LinearRegression
_regressor1 = LinearRegression()
_regressor1.fit(X3_train,y3_train)

LinearRegression()

In [ ]:
y3_pred1 = _regressor1.predict(X3_test)
for i in range(len(y3_pred1)):
    y3_pred1[i] = round(y3_pred1[i])
print(np.concatenate((y3_pred1.reshape(len(y3_pred1),1),y3_test.reshape(len(y3_test),1)),1))

[[76. 76.]
 [66. 67.]
 [67. 66.]
 ...
 [66. 66.]
 [83. 83.]
 [58. 57.]]


In [ ]:
_r2_1 = r2_score(y3_test,y3_pred1)
print("{:.3f}".format(_r2_1))

0.896


In [ ]:
from sklearn.preprocessing import PolynomialFeatures
_poly_reg = PolynomialFeatures(degree = 2)
X3_poly = poly_reg.fit_transform(X3_train)
_lin_reg = LinearRegression()
_regressor2 = lin_reg.fit(X3_poly,y3_train)

In [ ]:
y3_pred2 = _regressor2.predict(_poly_reg.fit_transform(X3_test))
for i in range(len(y3_pred2)):
    y3_pred2[i] = round(y3_pred2[i])
print(np.concatenate((y3_pred2.reshape(len(y3_pred2),1),y3_test.reshape(len(y3_test),1)),1))

[[77. 76.]
 [68. 67.]
 [66. 66.]
 ...
 [66. 66.]
 [83. 83.]
 [57. 57.]]


In [ ]:
_r2_2 = r2_score(y3_test,y3_pred2)
print("{:.3f}".format(_r2_2))

0.973


In [ ]:
_regressor3 = SVR(kernel='rbf')
_regressor3.fit(X3_train,y3_train)

SVR()

In [ ]:
y3_pred3 = _regressor3.predict(X3_test)
for i in range(len(y3_pred3)):
    y3_pred3[i] = round(y3_pred3[i])
print(np.concatenate((y3_pred3.reshape(len(y3_pred3),1),y3_test.reshape(len(y3_test),1)),1))

[[77. 76.]
 [68. 67.]
 [66. 66.]
 ...
 [68. 66.]
 [83. 83.]
 [57. 57.]]


In [ ]:
_r2_3 = r2_score(y3_test,y3_pred3)
print("{:.3f}".format(_r2_3))

0.971


In [ ]:
_regressor4 = DecisionTreeRegressor(random_state=0)
_regressor4.fit(X3_train,y3_train)

DecisionTreeRegressor(random_state=0)

In [ ]:
y3_pred4 = _regressor4.predict(X3_test)
for i in range(len(y3_pred4)):
    y3_pred4[i] = round(y3_pred4[i])
print(np.concatenate((y3_pred4.reshape(len(y3_pred4),1),y3_test.reshape(len(y3_test),1)),1))

[[79. 76.]
 [64. 67.]
 [67. 66.]
 ...
 [69. 66.]
 [80. 83.]
 [56. 57.]]


In [ ]:
_r2_4 = r2_score(y3_test,y3_pred4)
print("{:.3f}".format(_r2_4))

0.912


In [ ]:
_regressor5 = RandomForestRegressor(n_estimators=40,random_state=0)
_regressor5.fit(X3_train,y3_train)

RandomForestRegressor(n_estimators=40, random_state=0)

In [ ]:
y3_pred5 = _regressor5.predict(X3_test)
for i in range(len(y3_pred5)):
    y3_pred5[i] = round(y3_pred5[i])
print(np.concatenate((y3_pred5.reshape(len(y3_pred5),1),y3_test.reshape(len(y3_test),1)),1))

[[77. 76.]
 [67. 67.]
 [67. 66.]
 ...
 [66. 66.]
 [81. 83.]
 [55. 57.]]


In [ ]:
_r2_5 = r2_score(y3_test,y3_pred5)
print("{:.3f}".format(_r2_5))

0.966


###***Selected Algorithm - Polynomial Regression***